bourseapp/api/urls.py
from django.conf.urls import url

from rest_framework.urlpatterns import format_suffix_patterns

from . import views
from .views import *

app_name = 'api-bourseapp'

urlpatterns = [
    url(r'^Category$', views.CategoryAPIView.as_view(), name='post-listcreate'),
    # url(r'^Category/(?P<pk>\d+)/$', views.CategoryRudView.as_view(), name='post-rud'),

    url(r'^Symbols$', views.SymbolsAPIView.as_view(), name='symbols-view'),
    url(r'^chart-symbols$', views.ChartSymbolsAPIView.as_view(), name='chart-symbols'),
    url(r'^user-list$', views.UserList.as_view(), name='user-list'),

    url(r'^add-symbol-analyze$', views.AddSymbolAnalyze, name='add-symbol-analyze'),
    url(r'^list-symbol-analyze$', views.ListSymbolAnalyze.as_view(), name='list-symbol-analyze'),

    url(r'^add-symbol-portfolio$', views.AddPortfolio, name='add-symbol-portfolio'),
    url(r'^list-symbol-portfolio$', views.ListPortfolio.as_view(), name='list-symbol-portfolio'),

    # url(r'^set-candle$', views.UserList.as_view(), name='user-list'),

    url(r'^ChatMessage$', views.ChatMessageAPIView.as_view(), name='post-listcreate-chatMessage'),
    url(r'^ChatMessage/(?P<pk>\d+)/$', views.ChatMessageRudView.as_view(), name='post-rud-chatMessage'),

    url(r'^TechnicalUser$', views.TechnicalUserAPIView.as_view(), name='post-listcreate-technicalUser'),
    url(r'^TechnicalUser/(?P<pk>\d+)/$', views.TechnicalUserRudView.as_view(), name='post-rud-technicalUser'),

    url(r'^ChartBazaar$', views.ChartView, name='chart-bazaar-view'),
    url(r'^(?P<company_id>[0-9]+)/chart-detail/$', views.chart_detail, name='chart-detail'),
    url(r'^(?P<company_name>[a-zA-Z]+)/(?P<time_frame>[a-zA-Z0-9]+)/symbol-candle/$', views.symbol_candle, name='symbol-candle'),
    url(r'^symbol-candle-list$', views.SymbolCandleListAPIView.as_view(), name='post-symbol-candle-list'),

    url(r'^(?P<company_name>[a-zA-Z]+)/(?P<time_frame>[a-zA-Z0-9]+)/symbol-candle-json/$', views.symbol_candle_json,
        name='symbol-candle-json'),
    # url(r'^(?P<company_name>[a-zA-Z]+)/(?P<time_frame>[a-zA-Z0-9]+)/(?P<last_date>[a-zA-Z0-9]+)/symbol-candle-file/$'
    #     , views.symbol_candle_file, name='symbol-candle-file'),
    url(r'^(?P<company_name>[a-zA-Z_]+)/(?P<time_frame>[a-zA-Z0-9]+)/(?P<last_date>\d{4}-\d{2}-\d{2})/symbol-candle-file/$'
        , views.symbol_candle_file, name='symbol-candle-file'),
    url(r'^symbol-candle-json-list$', views.SymbolCandleJsonListAPIView.as_view(), name='symbol-candle-json-list'),
    url(r'^symbol-candle-json-list-title$', views.SymbolListTitle, name='csymbol-candle-json-list-title'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

bourseapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'bourseapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # manager panel urls
    url(r'^manager-panel/$', views.manager_panel, name='manager-panel'),
    url(r'^user-panel/$', views.user_panel, name='user-panel'),
    url(r'^(?P<user_id>[0-9]+)/user-approve/$', views.user_approve, name='user-approve'),
    url(r'^(?P<user_id>[0-9]+)/(?P<status>[0-9]+)/user-vip/$', views.user_vip, name='user-vip'),

    # message urls
    url(r'^messenger/$', views.messenger, name='messenger'),

    # category urls
    url(r'^category-list/$', views.category_list, name='category-list'),
    url(r'^(?P<category_id>[0-9]+)/category-detail/$', views.category_detail, name='category-detail'),

    # company urls
    url(r'^company-list/$', views.company_list, name='company-list'),
    url(r'^(?P<company_id>[0-9]+)/company-detail/$', views.company_detail, name='company-detail'),
    url(r'^(?P<company_id>[0-9]+)/company-technical-view/$', views.company_technical_view, name='company-technical-view'),
    url(r'^company-analyzed/$', views.company_analyzed, name='company-analyzed'),

    # new urls
    url(r'^news-list/$', views.new_list, name='news-list'),
    url(r'^news-create/$', views.news_create, name='news-create'),
    url(r'^(?P<news_id>[0-9]+)/news-detail/$', views.news_detail, name='news-detail'),
    url(r'^(?P<news_id>[0-9]+)/news-approve/$', views.news_approve, name='news-approve'),
    url(r'^news-important/$', views.news_important, name='news-important'),
    # path('create', views.ContactCreate.as_view(), name='contact_create'),

    # technical urls
    url(r'^technical-list/$', views.technical_list, name='technical-list'),
    url(r'^(?P<technical_id>[0-9]+)/technical-detail/$', views.technical_detail, name='technical-detail'),

    # webinar urls
    url(r'^webinar-list/$', views.webinar_list, name='webinar-list'),
    url(r'^(?P<webinar_id>[0-9]+)/webinar-detail/$', views.webinar_detail, name='webinar-detail'),

    # bazaar urls
    url(r'^bazzar-list/$', views.bazaar_list, name='bazaar-list'),
    url(r'^(?P<bazaar_id>[0-9]+)/bazaar-detail/$', views.bazaar_detail, name='bazaar-detail'),

    # fundamental urls
    url(r'^fundamental-list/$', views.fundamental_list, name='fundamental-list'),
    url(r'^(?P<fundamental_id>[0-9]+)/fundamental-detail/$', views.fundamental_detail, name='fundamental-detail'),

    # tutorial urls
    url(r'^tutorial-list/$', views.tutorial_list, name='tutorial-list'),
    url(r'^(?P<tutorial_id>[0-9]+)/tutorial-detail/$', views.tutorial_detail, name='tutorial-detail'),
    url(r'^(?P<tutorialCategory_id>[0-9]+)/tutorial-category/$', views.tutorial_category, name='tutorial-category'),
    url(r'^(?P<tutorialSubCategory_id>[0-9]+)/tutorial-subCategory/$', views.tutorial_subCategory, name='tutorial-subCategory'),

    # message urls
    url(r'^message-list/$', views.message_list, name='message-list'),

]

bourseapp/templates/bourseapp/symbols/symbols_analyzed.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% load auth_extras %}
{% block title %}
    <title>گروه های بورسیا</title>
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}



    <div class="container my-5">

        <!-- Section -->
        <section>

            <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">آرشیو</h6>
            <h3 class="font-weight-bold text-center dark-grey-text pb-2">تمامی نمادها</h3>
            <hr class="w-header my-4">
            <p class="lead text-center text-muted pt-2 mb-5">لیست تمامی نمادهایی که در سایت مورد بررسی قرار گرفته اند.</p>

            <!-- Search form -->
            <form class="form-inline d-flex justify-content-center md-form form-sm mt-0">
                <i class="fas fa-search ml-2" aria-hidden="true"></i>
                <input id="search-symbols-analyzed" class="form-control form-control-sm ml-3 w-75" type="text" placeholder="جست و جو"
                       aria-label="Search">
            </form>
            <div class="row">
                {% for cats in categories %}
                    <!-- Grid column -->
                    <div class="col-lg-3 col-md-6 mc-col-symbols-analyze">
                        {% for cat in cats %}
                            <!-- Panel -->
                            <div class="card mb-4 mc-category-symbols-analyze">

                                <div class="card-header white-text primary-color">
                                     <a href="{% url 'bourseapp:category-detail' cat.category.id %}" class="text-white">{{ cat.category.title }}</a>
                                </div>

                                <div class="card-body text-center px-4">
                                    <div class="list-group list-group-flush">
                                        {% for symbol in cat.symbols %}
                                            <div  value="{{ symbol.symbol }}" class="mc-symbol-tile">
                                                <div class="row list-group-item d-flex justify-content-between dark-grey-text mt-0 mb-0">


                                                    <a href="{% url 'bourseapp:company-detail' symbol.id %}" class="">
                                                        {% if symbol.pic %}
                                                            <img src="{{ symbol.pic.url }}" alt="" class="img-fluid rounded-circle img-thumbnail" style="height: 40px; width: 40px; object-fit: contain">
                                                        {% else %}
                                                            <i class="fas fa-chart-bar fa-lg blue p-2 img-fluid rounded-circle img-thumbnail text-white" style="height: 40px; width: 40px; object-fit: contain"></i>
                                                        {% endif %}
                                                        {{ symbol.symbol }}
                                                    </a>
                                                    <a href="{% url 'bourseapp:company-technical-view' symbol.id %}" class="flex-left ml-2"><i class="fa fa-analytics"></i></a>

                                                </div>
                                            </div>
                                        {% endfor %}

                                    </div>
                                </div>

                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div> <!-- end row -->

        </section>
        <!-- Section -->

    </div>

    <!-- base url address -->
    <input type="hidden" id="url-base" data-url="http://{{ request.get_host }}/" />
    <input type="hidden" id="url-symbol" data-url="{% url 'api-bourseapp:symbols-view' %}" />

    <input type="hidden" id="symbol-page-is-superuser" data-state="{{ request.user.is_superuser }}">


{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="{% static 'bourseapp/js/pages/symbols_analyzed.js' %}"></script>
{% endblock %}