bourseapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'bourseapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # manager panel urls
    url(r'^manager-panel/$', views.manager_panel, name='manager-panel'),
    url(r'^user-panel/$', views.user_panel, name='user-panel'),
    url(r'^(?P<user_id>[0-9]+)/user-approve/$', views.user_approve, name='user-approve'),
    url(r'^(?P<user_id>[0-9]+)/(?P<status>[0-9]+)/user-vip/$', views.user_vip, name='user-vip'),

    # message urls
    url(r'^messenger/$', views.messenger, name='messenger'),

    # category urls
    url(r'^category-list/$', views.category_list, name='category-list'),
    url(r'^(?P<category_id>[0-9]+)/category-detail/$', views.category_detail, name='category-detail'),

    # company urls
    url(r'^company-list/$', views.company_list, name='company-list'),
    url(r'^(?P<company_id>[0-9]+)/company-detail/$', views.company_detail, name='company-detail'),
    url(r'^(?P<company_id>[0-9]+)/company-technical-view/$', views.company_technical_view, name='company-technical-view'),
    url(r'^company-analyzed/$', views.company_analyzed, name='company-analyzed'),

    # new urls
    url(r'^news-list/$', views.new_list, name='news-list'),
    url(r'^news-create/$', views.news_create, name='news-create'),
    url(r'^(?P<news_id>[0-9]+)/news-detail/$', views.news_detail, name='news-detail'),
    url(r'^(?P<news_id>[0-9]+)/news-approve/$', views.news_approve, name='news-approve'),
    url(r'^news-important/$', views.news_important, name='news-important'),
    # path('create', views.ContactCreate.as_view(), name='contact_create'),

    # technical urls
    url(r'^technical-list/$', views.technical_list, name='technical-list'),
    url(r'^(?P<technical_id>[0-9]+)/technical-detail/$', views.technical_detail, name='technical-detail'),

    # webinar urls
    url(r'^webinar-list/$', views.webinar_list, name='webinar-list'),
    url(r'^(?P<webinar_id>[0-9]+)/webinar-detail/$', views.webinar_detail, name='webinar-detail'),

    # bazaar urls
    url(r'^bazzar-list/$', views.bazaar_list, name='bazaar-list'),
    url(r'^(?P<bazaar_id>[0-9]+)/bazaar-detail/$', views.bazaar_detail, name='bazaar-detail'),

    # fundamental urls
    url(r'^fundamental-list/$', views.fundamental_list, name='fundamental-list'),
    url(r'^(?P<fundamental_id>[0-9]+)/fundamental-detail/$', views.fundamental_detail, name='fundamental-detail'),

    # tutorial urls
    url(r'^tutorial-list/$', views.tutorial_list, name='tutorial-list'),
    url(r'^(?P<tutorial_id>[0-9]+)/tutorial-detail/$', views.tutorial_detail, name='tutorial-detail'),
    url(r'^(?P<tutorialCategory_id>[0-9]+)/tutorial-category/$', views.tutorial_category, name='tutorial-category'),
    url(r'^(?P<tutorialSubCategory_id>[0-9]+)/tutorial-subCategory/$', views.tutorial_subCategory, name='tutorial-subCategory'),

    # message urls
    url(r'^message-list/$', views.message_list, name='message-list'),

]

bourseapp/templates/bourseapp/tutorials/tutorialCategory.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% load social_share %}
{% block title %}
    <title> {{ tutorial.title }}</title>
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}


    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables.min.css' %}"><!-- MDBootstrap Datatables  -->
    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables-select.min.css' %}"><!-- MDBootstrap Datatables  -->


    <!-- left section -->
    <div class="col-md-12 mb-4">
        {% for cat in tutorialSubCat %}

            <!--Tutorial-->
            <div class="card mt-3">
                <div class="card-header" role="tab">
                    <a href="{% url 'bourseapp:tutorial-subCategory' cat.id %}">
                        <h5 class="text-center font-weight-bold mb-1">آموزش های {{ cat.title }}</h5>
                    </a>
                </div>
                <!--Card content-->
                <div class="card-body d-sm-flex justify-content-between mx-0">

                    <!-- Grid row -->
                    <div class="row">

                        <!-- Grid column -->
                        <div class="col-lg-7 mb-4 align-self-center text-center text-lg-right">

                            <h2 class="h2 mb-5">
                                {{ cat.title }}

                                {% if request.user.is_superuser %}
{#                                    <a href="{% url 'admin:bourseapp_tutorial_change' tutorial.id %}" target="_blank"><i class="fa fa-edit" style="color: #0d5bdd; font-size: 16px"></i></a>#}
{#                                    <a href="{% url 'admin:bourseapp_tutorial_delete' tutorial.id %}" target="_blank"><i class="fa fa-trash" style="color: #9f105c; font-size: 16px"></i></a>#}
                                {% endif %}
                            </h2>

                            <p class="font-weight-bold text-right">سطح: {{ cat.get_categoryLevel_display }}</p>
                            <p class="font-weight-bold text-right">دسته بندی: {{ cat.category }}</p>

                            <span class="badge badge-primary  float-left">{{ cat.user }}</span>
                            <span class="badge badge-primary  float-left ml-1">{{ cat.createAt|to_jalali:'%y/%m/%d' }}</span>
                            <div class="row mr-1">
                                {% post_to_telegram cat.title url '<i class="fab fa-telegram fa-lg "></i>' %}
                                {% post_to_twitter  cat.title url '<i class="fab fa-twitter fa-lg mr-2"></i>' %}
                                <a data-toggle="tooltip" title="فعال در موبایل ها" href="whatsapp://send?text=http://{{ request.get_host }}{{url}}  {{ cat.title }}" data-action="share/whatsapp/share">
                                    <i class="fab fa-whatsapp fa-lg mr-2"></i>
                                </a>
                            </div>

                            <p class="text-muted mb-4">{{ cat.description | safe }}</p>


                        </div>
                        <!-- Grid column -->

                        <!-- Grid column -->
                        <div class="col-lg-5 mb-4">

                            <!--  image -->
                            <div class="view overlay">

                                {% if cat.category == 'تحلیل بازار' %}
                                    <img class="img-fluid mx-auto" src="{% static 'bourseapp/images/tutorial_bazar.jpg' %}" alt="{{ tutorial.category }}">
                                {% elif cat.category == 'تحلیل بنیادی'%}
                                    <img class="img-fluid mx-auto" src="{% static 'bourseapp/images/tutorial_fundamental.png' %}" alt="{{ tutorial.category }}">
                                {% else %}
                                    <img class="img-fluid mx-auto" src="{% static 'bourseapp/images/tutorial_technical.png' %}" alt="{{ tutorial.category }}">
                                {% endif %}

                                <a>
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>

                        </div>
                        <!-- Grid column -->

                    </div>
                    <!-- Grid row -->

                </div>
            </div>

        {% endfor %}
    </div>


    <!-- base url address -->
    <input type="hidden" id="url-base" data-url="http://{{ request.get_host }}/" />

    <!-- selected category id -->
{#    <input type="hidden" id="category-selected-id" selected-id="-1">#}

    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'bourseapp/js/jquery.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/mdb.min.js' %}"></script>
    <!-- MDB table core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/addons/datatables.min.js' %}"></script><!-- MDBootstrap Datatables  -->
    <!-- MDB table core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/addons/datatables-select.min.js' %}"></script><!-- MDBootstrap Datatables  -->


{% endblock %}

bourseapp/templates/bourseapp/tutorials/tutorial_detail.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% load social_share %}
{% block title %}
    <title> {{ tutorial.title }}</title>

    <meta name="description" content="{{ tutorial.description|truncatechars:120 }}"/>
    <meta property="og:locale" content="fa_IR" />
    <meta property="og:type" content="tutorial" />
    <meta property="og:title" content="{{ tutorial.title }}" />
    <meta property="og:description" content="{{ tutorial.description|truncatechars:120 }}" />
    <meta property="og:url" content="{{ request.get_host }}{% url 'bourseapp:tutorial-detail' tutorial.id %}"/>
    <meta property="og:site_name" content="مدیابورس" />
    {% if tutorial.pic %}
        <meta property="og:image" content="{{ request.get_host }}{{ tutorial.pic.url }}" />
    {% endif %}
    <meta property="article:tag" content="بورس" />
    <meta property="article:tag" content="آموزش بورس" />
    <meta property="article:tag" content="بورس تهران" />
    <meta property="article:tag" content="{{ tutorial.subCategory.title }}" />
    <meta property="article:tag" content="{{ tutorial.subCategory.category.title }}" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:description" content="{{ tutorial.description|truncatechars:120 }}" />
    <meta name="twitter:title" content="{{ tutorial.title }}" />
    {% if tutorial.pic %}
        <meta name="twitter:image" content="{{ request.get_host }}{{ tutorial.pic.url }}" />
    {% endif %}
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}


    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables.min.css' %}"><!-- MDBootstrap Datatables  -->
    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables-select.min.css' %}"><!-- MDBootstrap Datatables  -->

    <div class="container mt-5">


        <!--Section: Content-->
        <section>

            <!-- Grid row -->
            <div class="row">

                <!-- Grid column -->
                <div class="col-lg-7 mb-4 align-self-center text-center text-lg-right">

                    <h2 class="h2 mb-5">
                        {{ tutorial.title }}

                        {% if request.user.is_superuser %}
                            <a href="{% url 'admin:bourseapp_tutorial_change' tutorial.id %}" target="_blank"><i class="fa fa-edit" style="color: #0d5bdd; font-size: 16px"></i></a>
                            <a href="{% url 'admin:bourseapp_tutorial_delete' tutorial.id %}" target="_blank"><i class="fa fa-trash" style="color: #9f105c; font-size: 16px"></i></a>
                        {% endif %}
                    </h2>

                    <p class="font-weight-bold text-right">دسته بندی: {{ tutorial.category }}</p>

                    <span class="badge badge-primary  float-left">{{ tutorial.user }}</span>
                    <span class="badge badge-primary  float-left ml-1">{{ tutorial.createAt|to_jalali:'%y/%m/%d' }}</span>
                    <div class="row mr-1">
                        {% post_to_telegram tutorial.title url '<i class="fab fa-telegram fa-lg "></i>' %}
                        {% post_to_twitter  tutorial.title url '<i class="fab fa-twitter fa-lg mr-2"></i>' %}
                        <a data-toggle="tooltip" title="فعال در موبایل ها" href="whatsapp://send?text=http://{{ request.get_host }}{{url}}  {{ tutorial.title }}" data-action="share/whatsapp/share">
                            <i class="fab fa-whatsapp fa-lg mr-2"></i>
                        </a>
                    </div>

                    <p class="text-muted mb-4">{{ tutorial.description | safe }}</p>

                    {% if tutorial.file %}
                        <a href="{{ tutorial.file.url }}"  target="_blank" class="btn btn-cyan waves-effect btn-md ml-lg-0"><i class="fa fa-download fa-lg pr-1"></i> دانلود آموزش</a>
                    {% endif %}

                    {% if tutorial.externalLink %}
                        <a href="{{ tutorial.externalLink }}"  target="_blank" class="btn btn-cyan waves-effect btn-md ml-lg-0"><i class="fa fa-external-link fa-lg pr-1"></i> لینک آموزش</a>
                    {% endif %}

                    {% if tutorial.externalLink %}
                    {% endif %}
                    {{ tutorial.aparatEmbedCode|safe }}

                </div>
                <!-- Grid column -->

                <!-- Grid column -->
                <div class="col-lg-5 mb-4">

                    <!--  image -->
                    <div class="view overlay">

                        {% if tutorial.category == 'تحلیل بازار' %}
                            <img class="img-fluid mx-auto" src="{% static 'bourseapp/images/tutorial_bazar.jpg' %}" alt="{{ tutorial.category }}">
                        {% elif tutorial.category == 'تحلیل بنیادی'%}
                            <img class="img-fluid mx-auto" src="{% static 'bourseapp/images/tutorial_fundamental.png' %}" alt="{{ tutorial.category }}">
                        {% else %}
                            <img class="img-fluid mx-auto" src="{% static 'bourseapp/images/tutorial_technical.png' %}" alt="{{ tutorial.category }}">
                        {% endif %}


                        <a>
                            <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>

                </div>
                <!-- Grid column -->

            </div>
            <!-- Grid row -->

        </section>
        <!--Section: Content-->


    </div>





    <div class="d-none container my-5 py-5 z-depth-1">

        <!--Section: Content-->
        <section class="px-md-5 mx-md-5 dark-grey-text text-center text-lg-left">

            <!--Grid row-->
            <div class="row">
                <h3 class="font-weight-bold text-right">{{ tutorial.title }}</h3>

                <p class="font-weight-bold text-right">{{ tutorial.createAt|to_jalali:'%y/%m/%d' }}
                    <span class="badge badge-secondary  float-left"><small>{{ tutorial.user }}</small></span>
                </p>

                <a href="{{ tutorial.externalLink }}" target="_blank"><i class="fa fa-link"><span style="font-family: IRANSans"> لینک آموزش  </span></i></a>

                {% if tutorial.file %}
                    <a href="{{ tutorial.file }}" target="_blank">
                        {#                            <img src="{{ tutorial.file }}" class="img-fluid" alt="" style="width: 150px; height: 150px; object-fit: cover">#}
                        <i class="fa fa-download"></i>
                    </a>
                {% else %}
                    {#                        <img src="{% static 'bourseapp/images/news.png' %}" class="img-fluid" alt="" style="width: 150px; height: 150px; object-fit: cover">#}

                {% endif %}

            </div>
            <!--Grid row-->

            <hr>
            <p class="text-muted text-right text-justify" dir="rtl">{{ tutorial.description | safe  }}</p>


        </section>
        <!--Section: Content-->

    </div>

    <!-- base url address -->
    <input type="hidden" id="url-base" data-url="http://{{ request.get_host }}/" />

    <!-- selected category id -->
{#    <input type="hidden" id="category-selected-id" selected-id="-1">#}

{% endblock %}

{% block javascript %}
{% endblock %}

bourseapp/templates/bourseapp/tutorials/tutorial_subCat_list.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% load social_share %}
{% block title %}
    <title> {{ tutorial.title }}</title>

    <meta name="description" content="{{ tutorialSubCat.description|truncatechars:120 }}"/>
    <meta property="og:locale" content="fa_IR" />
    <meta property="og:type" content="tutorial" />
    <meta property="og:title" content="{{ tutorialSubCat.title }}" />
    <meta property="og:description" content="{{ tutorialSubCat.description|truncatechars:120 }}" />
    <meta property="og:url" content="{{ request.get_host }}{% url 'bourseapp:tutorial-subCategory' tutorialSubCat.id %}"/>
    <meta property="og:site_name" content="مدیابورس" />
    {% if tutorialSubCat.pic %}
        <meta property="og:image" content="{{ request.get_host }}{{ tutorialSubCat.pic.url }}" />
    {% endif %}
    <meta property="article:tag" content="بورس" />
    <meta property="article:tag" content="آموزش بورس" />
    <meta property="article:tag" content="بورس تهران" />
    <meta property="article:tag" content="{{ tutorialSubCat.category.title }}" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:description" content="{{ tutorialSubCat.description|truncatechars:120 }}" />
    <meta name="twitter:title" content="{{ tutorialSubCat.title }}" />
    {% if tutorialSubCat.pic %}
        <meta name="twitter:image" content="{{ request.get_host }}{{ tutorialSubCat.pic.url }}" />
    {% endif %}
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}


    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables.min.css' %}"><!-- MDBootstrap Datatables  -->
    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables-select.min.css' %}"><!-- MDBootstrap Datatables  -->


    <!-- header section -->
    <div class="col-md-12 mb-4">
        <!--Tutorial-->
        <div class="card mt-3">
            <div class="card-header" role="tab">
                <h5 class="text-center font-weight-bold mb-1">{{ tutorialSubCat.title }}</h5>
            </div>
            <!--Card content-->
        </div>

    <div class="row container-fluid mt-4">
        {% for tutorial in tutorials %}

                <figure class="col-md-3 d-md-inline-block">
                    <a href="{% url 'bourseapp:tutorial-detail' tutorial.id %}"
                       data-size="1600x1067">
                        <div class="view rounded">
                            {% if tutorial.category == 'تحلیل بازار' %}
                                <img src="{% static 'bourseapp/images/tutorial_bazar.jpg' %}" class="img-fluid" alt="{{ tutorial.title }}">
                            {% elif tutorial.category == 'تحلیل بنیادی'%}
                                <img src="{% static 'bourseapp/images/tutorial_fundamental.png' %}" class="img-fluid" alt="{{ tutorial.title }}">
                            {% else %}
                                <img src="{% static 'bourseapp/images/tutorial_technical.png' %}" class="img-fluid" alt="{{ tutorial.title }}">
                            {% endif %}

                            <div class="mask flex-center rgba-black-strong">
                            </div>
                        </div>

                        <!--Caption-->
                        <div class="carousel-caption">
                            <div class="animated fadeInDown">
                                <i class="fa fa-video mb-1" style="font-size: 24px"></i>
                                <h6 class="h6-responsive smaller">{{ tutorial.title|truncatechars:50 }} </h6>
                                {% if tutorial.description %}
                                    <p>({{ tutorial.description|truncatechars:50 }})</p>
                                {% else %}
                                    <p>-</p>
                                {% endif %}
                            </div>
                        </div>
                        <!--Caption-->
                    </a>
                </figure>


        {% endfor %}
    </div>



    </div>


    <!-- base url address -->
    <input type="hidden" id="url-base" data-url="http://{{ request.get_host }}/" />

    <!-- selected category id -->
{#    <input type="hidden" id="category-selected-id" selected-id="-1">#}

{% endblock %}

{% block javascript %}
{% endblock %}