bourseapp/api/urls.py
from django.conf.urls import url

from rest_framework.urlpatterns import format_suffix_patterns

from . import views
from .views import *

app_name = 'api-bourseapp'

urlpatterns = [
    url(r'^Category$', views.CategoryAPIView.as_view(), name='post-listcreate'),
    # url(r'^Category/(?P<pk>\d+)/$', views.CategoryRudView.as_view(), name='post-rud'),

    url(r'^Symbols$', views.SymbolsAPIView.as_view(), name='symbols-view'),
    url(r'^chart-symbols$', views.ChartSymbolsAPIView.as_view(), name='chart-symbols'),
    url(r'^user-list$', views.UserList.as_view(), name='user-list'),

    url(r'^add-symbol-analyze$', views.AddSymbolAnalyze, name='add-symbol-analyze'),
    url(r'^list-symbol-analyze$', views.ListSymbolAnalyze.as_view(), name='list-symbol-analyze'),

    url(r'^add-symbol-portfolio$', views.AddPortfolio, name='add-symbol-portfolio'),
    url(r'^list-symbol-portfolio$', views.ListPortfolio.as_view(), name='list-symbol-portfolio'),

    # url(r'^set-candle$', views.UserList.as_view(), name='user-list'),

    url(r'^ChatMessage$', views.ChatMessageAPIView.as_view(), name='post-listcreate-chatMessage'),
    url(r'^ChatMessage/(?P<pk>\d+)/$', views.ChatMessageRudView.as_view(), name='post-rud-chatMessage'),

    url(r'^TechnicalUser$', views.TechnicalUserAPIView.as_view(), name='post-listcreate-technicalUser'),
    url(r'^TechnicalUser/(?P<pk>\d+)/$', views.TechnicalUserRudView.as_view(), name='post-rud-technicalUser'),

    url(r'^ChartBazaar$', views.ChartView, name='chart-bazaar-view'),
    url(r'^(?P<company_id>[0-9]+)/chart-detail/$', views.chart_detail, name='chart-detail'),
    url(r'^(?P<company_name>[a-zA-Z]+)/(?P<time_frame>[a-zA-Z0-9]+)/symbol-candle/$', views.symbol_candle, name='symbol-candle'),
    url(r'^symbol-candle-list$', views.SymbolCandleListAPIView.as_view(), name='post-symbol-candle-list'),

    url(r'^(?P<company_name>[a-zA-Z]+)/(?P<time_frame>[a-zA-Z0-9]+)/symbol-candle-json/$', views.symbol_candle_json,
        name='symbol-candle-json'),
    # url(r'^(?P<company_name>[a-zA-Z]+)/(?P<time_frame>[a-zA-Z0-9]+)/(?P<last_date>[a-zA-Z0-9]+)/symbol-candle-file/$'
    #     , views.symbol_candle_file, name='symbol-candle-file'),
    url(r'^(?P<company_name>[a-zA-Z_]+)/(?P<time_frame>[a-zA-Z0-9]+)/(?P<last_date>\d{4}-\d{2}-\d{2})/symbol-candle-file/$'
        , views.symbol_candle_file, name='symbol-candle-file'),
    url(r'^symbol-candle-json-list$', views.SymbolCandleJsonListAPIView.as_view(), name='symbol-candle-json-list'),
    url(r'^symbol-candle-json-list-title$', views.SymbolListTitle, name='csymbol-candle-json-list-title'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

bourseapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'bourseapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # manager panel urls
    url(r'^manager-panel/$', views.manager_panel, name='manager-panel'),
    url(r'^user-panel/$', views.user_panel, name='user-panel'),
    url(r'^(?P<user_id>[0-9]+)/user-approve/$', views.user_approve, name='user-approve'),
    url(r'^(?P<user_id>[0-9]+)/(?P<status>[0-9]+)/user-vip/$', views.user_vip, name='user-vip'),

    # message urls
    url(r'^messenger/$', views.messenger, name='messenger'),

    # category urls
    url(r'^category-list/$', views.category_list, name='category-list'),
    url(r'^(?P<category_id>[0-9]+)/category-detail/$', views.category_detail, name='category-detail'),

    # company urls
    url(r'^company-list/$', views.company_list, name='company-list'),
    url(r'^(?P<company_id>[0-9]+)/company-detail/$', views.company_detail, name='company-detail'),
    url(r'^(?P<company_id>[0-9]+)/company-technical-view/$', views.company_technical_view, name='company-technical-view'),
    url(r'^company-analyzed/$', views.company_analyzed, name='company-analyzed'),

    # new urls
    url(r'^news-list/$', views.new_list, name='news-list'),
    url(r'^news-create/$', views.news_create, name='news-create'),
    url(r'^(?P<news_id>[0-9]+)/news-detail/$', views.news_detail, name='news-detail'),
    url(r'^(?P<news_id>[0-9]+)/news-approve/$', views.news_approve, name='news-approve'),
    url(r'^news-important/$', views.news_important, name='news-important'),
    # path('create', views.ContactCreate.as_view(), name='contact_create'),

    # technical urls
    url(r'^technical-list/$', views.technical_list, name='technical-list'),
    url(r'^(?P<technical_id>[0-9]+)/technical-detail/$', views.technical_detail, name='technical-detail'),

    # webinar urls
    url(r'^webinar-list/$', views.webinar_list, name='webinar-list'),
    url(r'^(?P<webinar_id>[0-9]+)/webinar-detail/$', views.webinar_detail, name='webinar-detail'),

    # bazaar urls
    url(r'^bazzar-list/$', views.bazaar_list, name='bazaar-list'),
    url(r'^(?P<bazaar_id>[0-9]+)/bazaar-detail/$', views.bazaar_detail, name='bazaar-detail'),

    # fundamental urls
    url(r'^fundamental-list/$', views.fundamental_list, name='fundamental-list'),
    url(r'^(?P<fundamental_id>[0-9]+)/fundamental-detail/$', views.fundamental_detail, name='fundamental-detail'),

    # tutorial urls
    url(r'^tutorial-list/$', views.tutorial_list, name='tutorial-list'),
    url(r'^(?P<tutorial_id>[0-9]+)/tutorial-detail/$', views.tutorial_detail, name='tutorial-detail'),
    url(r'^(?P<tutorialCategory_id>[0-9]+)/tutorial-category/$', views.tutorial_category, name='tutorial-category'),
    url(r'^(?P<tutorialSubCategory_id>[0-9]+)/tutorial-subCategory/$', views.tutorial_subCategory, name='tutorial-subCategory'),

    # message urls
    url(r'^message-list/$', views.message_list, name='message-list'),

]

bourseapp/templates/bourseapp/Messages/messenger.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% load humanize %}
{% load auth_extras %}
{% block title %}
    <title>پیام ها</title>
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}

    <!-- Material Design Bootstrap table -->
{#    <link rel="stylesheet" href="{% static 'bourseapp/css/Pages/messanger.css' %}">#}

    <p class="text-white mb-0">.</p>
    <div class="container" dir="ltr">

        <div class="card grey lighten-3 chat-room mb-3">
            <div class="card-body">

                <!-- Grid row -->
                <div class="row px-lg-2 px-2">

                    <!-- messege -->
                    <div class="col-md-6 col-xl-8 pl-md-3 px-lg-auto px-0">

                        <div class="chat-message mr-3">

                            <ul id="container-message-members" class="list-unstyled chat border" style="width: 100%; height: 300px; overflow: auto"></ul>
                            <div class="form-group basic-textarea"  style="position: relative; bottom: 0;">
                                <textarea id="txt-messageBox" dir="rtl" class="form-control pl-2 my-0" id="exampleFormControlTextarea2" rows="3" placeholder="متن خود را در این قسمت وارد کنید ..."></textarea>
                            </div>
                            {% if request.user|has_group:"level1" or user.is_superuser %}
                                <button type="button" onclick="sendMessage(true)" class="btn btn-info btn-rounded btn-sm waves-effect waves-light float-right">ارسال <i class="fa fa-paper-plane ml-1"></i></button>
                            {% else %}
                                <button type="button" onclick="sendMessage()" class="btn btn-info btn-rounded btn-sm waves-effect waves-light float-right">ارسال <i class="fa fa-paper-plane ml-1"></i></button>
                            {% endif %}
                        </div>

                    </div>

                    <!-- members -->
                    <div class="col-md-6 col-xl-4 px-0 border">

                        {% if request.user|has_group:"level1" or user.is_superuser %}
                            <div class="white px-3 pt-3 pb-1 rounded mb-2" dir="rtl">
                                <p>تعداد پیام های خوانده نشده: <strong>{{ unReadMsgCount }}</strong></p>
                            </div>
                        {% endif %}

                        <div class="white px-3 pt-3 pb-1 rounded" dir="rtl">
                        <!-- Search form -->
                            <form class="form-inline">
                                <i class="fas fa-search ml-2" aria-hidden="true"></i>

                                {% if request.user|has_group:"level1" or user.is_superuser %}
                                    <input id="search-member" class="form-control form-control-sm ml-3" type="text" placeholder="جست وجو" aria-label="Search" style="width: 90%">
                                {% else %}
                                    <input class="form-control form-control-sm ml-3" type="text" placeholder="جست وجو" aria-label="Search" style="width: 90%">
                                {% endif %}
                            </form>
                            <hr>
                            <ul class="list-unstyled friend-list">
                                <!-- admin -->
                                <li  id="admin-member" value="{{ admin_user.id }}" data-page="1" class="myclass-member-tile active grey lighten-3 p-1 border-bottom" style="margin-right: -30px">
                                    <a class="d-flex justify-content-between" onclick="selectMember('admin-member', false, true)">
                                        <img src="{% static 'bourseapp/images/admin_placeholder.jfif' %}" alt="avatar" class="avatar rounded-circle d-flex align-self-center img-thumbnail"
                                             style="object-fit: contain; width: 60px; height: 60px; ">
                                        <div class="text-small text-right mr-1">
                                            <small dir="ltr">@admin</small>
                                            <p class="last-message text-muted mb-0">ارتباط با ادمین ها</p>
                                        </div>
                                        <div class="text-small text-right" >
                                            <p class="text-smaller text-muted mb-0">Just now</p>
                                            <span class="badge badge-danger float-left d-none">1</span>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                            <!-- members -->
                            <ul id="container-member-list" class="list-unstyled friend-list"></ul>

                            <!-- admin message members -->
                            {% if request.user|has_group:"level1" or user.is_superuser %}
                                <ul class="list-unstyled friend-list">
                                    {% for member in member_msg2admin %}
                                        <li  id="member-msg2admin-{{ member.account.id }}" value="{{ member.account.id }}" data-page="1" class="myclass-member-tile active grey lighten-3 p-1 border-bottom" style="margin-right: -30px">
                                            <a class="d-flex justify-content-between" onclick="selectMember('member-msg2admin-{{ member.account.id }}', true, true)">
                                                <img src="{% static 'bourseapp/images/Blank-Placeholder.jpg' %}" alt="avatar" class="avatar rounded-circle d-flex align-self-center img-thumbnail"
                                                     style="object-fit: contain; width: 60px; height: 60px; ">
                                                <div class="text-small text-right mr-1">
                                                    <small dir="ltr">@{{ member.account.username }}</small>
                                                    <p class="last-message text-muted mb-0">{{ member.account.first_name }} {{ member.account.last_name }}</p>
                                                </div>
                                                <div class="text-small text-right" >
{#                                                    <p dir="ltr" class="text-smaller text-muted mb-0 small">{{ member.account.last_login|to_jalali:'%y/%m/%d %H:%M:%S' }}</p>#}
                                                    <p dir="ltr" class="text-smaller text-muted mb-0 small">{{ member.account.last_login|naturaltime }}</p>
                                                    {% if member.unReadMsg > 0 %}
                                                    <span id="member-unReadMsgCount-{{ member.account.id }}" class="badge badge-danger float-left">{{ member.unReadMsg }}</span>
                                                    {% endif %}
                                                </div>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </div>

                    </div>

                </div>
                <!-- Grid row -->

            </div>
        </div>


    </div>
{#    <div class="form-group basic-textarea" style="position: fixed; bottom: 0; width: 100%">#}
{#        <textarea class="form-control pl-2 my-0" id="exampleFormControlTextarea2" rows="3" placeholder="Type your message here..."></textarea>#}
{#    </div>#}

    <img id="img-member-placeholder" class="d-none" src="{% static 'bourseapp/images/Blank-Placeholder.jpg' %}" >
    <img id="img-admins-placeholder" class="d-none" src="{% static 'bourseapp/images/admin_placeholder.jfif' %}" >
    <input type="hidden" id="url-member-list" data-url="{% url 'api-bourseapp:user-list'%}" />
    <input type="hidden" id="url-message-create" data-url="{% url 'api-bourseapp:post-listcreate-chatMessage'%}" />
    <input type="hidden" id="url-message-delete" data-url="{% url 'api-bourseapp:post-rud-chatMessage' 1234%}" />

{% endblock %}


{% block javascript %}

    <script>
        var csrftoken = '{{ csrf_token }}';
        var user_id = '{{ user.id }}';
    </script>
    <script src="{% static 'bourseapp/js/pages/messanger.js' %}"></script>
{% endblock %}