bourseapp/urls.py
from django.conf.urls import url
from . import views

app_name = 'bourseapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    # manager panel urls
    url(r'^manager-panel/$', views.manager_panel, name='manager-panel'),
    url(r'^user-panel/$', views.user_panel, name='user-panel'),
    url(r'^(?P<user_id>[0-9]+)/user-approve/$', views.user_approve, name='user-approve'),
    url(r'^(?P<user_id>[0-9]+)/(?P<status>[0-9]+)/user-vip/$', views.user_vip, name='user-vip'),

    # message urls
    url(r'^messenger/$', views.messenger, name='messenger'),

    # category urls
    url(r'^category-list/$', views.category_list, name='category-list'),
    url(r'^(?P<category_id>[0-9]+)/category-detail/$', views.category_detail, name='category-detail'),

    # company urls
    url(r'^company-list/$', views.company_list, name='company-list'),
    url(r'^(?P<company_id>[0-9]+)/company-detail/$', views.company_detail, name='company-detail'),
    url(r'^(?P<company_id>[0-9]+)/company-technical-view/$', views.company_technical_view, name='company-technical-view'),
    url(r'^company-analyzed/$', views.company_analyzed, name='company-analyzed'),

    # new urls
    url(r'^news-list/$', views.new_list, name='news-list'),
    url(r'^news-create/$', views.news_create, name='news-create'),
    url(r'^(?P<news_id>[0-9]+)/news-detail/$', views.news_detail, name='news-detail'),
    url(r'^(?P<news_id>[0-9]+)/news-approve/$', views.news_approve, name='news-approve'),
    url(r'^news-important/$', views.news_important, name='news-important'),
    # path('create', views.ContactCreate.as_view(), name='contact_create'),

    # technical urls
    url(r'^technical-list/$', views.technical_list, name='technical-list'),
    url(r'^(?P<technical_id>[0-9]+)/technical-detail/$', views.technical_detail, name='technical-detail'),

    # webinar urls
    url(r'^webinar-list/$', views.webinar_list, name='webinar-list'),
    url(r'^(?P<webinar_id>[0-9]+)/webinar-detail/$', views.webinar_detail, name='webinar-detail'),

    # bazaar urls
    url(r'^bazzar-list/$', views.bazaar_list, name='bazaar-list'),
    url(r'^(?P<bazaar_id>[0-9]+)/bazaar-detail/$', views.bazaar_detail, name='bazaar-detail'),

    # fundamental urls
    url(r'^fundamental-list/$', views.fundamental_list, name='fundamental-list'),
    url(r'^(?P<fundamental_id>[0-9]+)/fundamental-detail/$', views.fundamental_detail, name='fundamental-detail'),

    # tutorial urls
    url(r'^tutorial-list/$', views.tutorial_list, name='tutorial-list'),
    url(r'^(?P<tutorial_id>[0-9]+)/tutorial-detail/$', views.tutorial_detail, name='tutorial-detail'),
    url(r'^(?P<tutorialCategory_id>[0-9]+)/tutorial-category/$', views.tutorial_category, name='tutorial-category'),
    url(r'^(?P<tutorialSubCategory_id>[0-9]+)/tutorial-subCategory/$', views.tutorial_subCategory, name='tutorial-subCategory'),

    # message urls
    url(r'^message-list/$', views.message_list, name='message-list'),

]

bourseapp/templates/bourseapp/bazaar_detail.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% load social_share %}
{% block title %}
    <title>تحلیل بازار {{ bazaar.company.symbol }}</title>

    <meta name="description" content="{{ bazaar.description|truncatechars:120 }}"/>
    <meta property="og:locale" content="fa_IR" />
    <meta property="og:type" content="website" />
    <meta property="og:title" content="{{ bazaar.title }}" />
    <meta property="og:description" content="{{ bazaar.description|truncatechars:120 }}" />
    <meta property="og:url" content="{{ request.get_host }}{% url 'bourseapp:bazaar-detail' bazaar.id %}"/>
    <meta property="og:site_name" content="مدیابورس: اخبار و آموزش بورس" />
    {% if bazaar.pic %}
        <meta property="og:image" content="{{ request.get_host }}{{ bazaar.pic.url }}" />
    {% endif %}
    <meta property="article:tag" content="بورس" />
    <meta property="article:tag" content="تحلیل بازار بورس" />
    <meta property="article:tag" content="بورس تهران" />
    <meta property="article:tag" content="{{ bazaar.company.symbol }}" />
    <meta property="article:tag" content="{{ bazaar.company.fullName }}" />

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:description" content="{{ bazaar.description|truncatechars:120 }}" />
    <meta name="twitter:title" content="{{ bazaar.title }}" />
    {% if bazaar.pic %}
        <meta name="twitter:image" content="{{ request.get_host }}{{ bazaar.pic.url }}" />
    {% endif %}
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}


    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables.min.css' %}"><!-- MDBootstrap Datatables  -->
    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables-select.min.css' %}"><!-- MDBootstrap Datatables  -->

    <div class="container my-5 py-5 z-depth-1">

        <!--Section: Content-->
        <section class="px-md-5 mx-md-5 dark-grey-text text-center text-lg-left">

            <!--Grid row-->
            <div class="row">

                <!--Grid column-->
                <div class="col-lg-6 mb-4 mb-lg-0 ">

                    <h3 class="font-weight-bold text-right">{{ bazaar.company.fullName }} ({{ bazaar.company.symbol }})</h3>

                    <p class="font-weight-bold text-right">{{ bazaar.title }} - {{ bazaar.createAt|to_jalali:'%y/%m/%d' }}
                    {% if user.is_authenticated%}
                        <a class=" text-right" href="{% url 'admin:bourseapp_bazaar_change' bazaar.id %}" target="_blank"><i class="fa fa-edit"></i></a>
                    {% endif %}
                    </p>
                    <div class="row mr-1">
                        {% post_to_telegram bazaar.title url '<i class="fab fa-telegram fa-lg "></i>' %}
                        {% post_to_twitter  bazaar.title url '<i class="fab fa-twitter fa-lg mr-2"></i>' %}
                        <a data-toggle="tooltip" title="فعال در موبایل ها" href="whatsapp://send?text=http://{{ request.get_host }}{{url}}  {{ bazaar.title }}" data-action="share/whatsapp/share">
                            <i class="fab fa-whatsapp fa-lg mr-2"></i>
                        </a>
                    </div>


                    {#                    <textarea class="form-control border-0 disabled text-muted" rows="5">#}
{#                        {{ news.description }}#}
{#                    </textarea>#}

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-6 mb-4 mb-lg-0 d-flex align-items-center justify-content-center">

                    {% if bazaar.pic %}
                        <a href="{{ bazaar.pic.url }}" target="_blank"><img src="{{ bazaar.pic.url }}" class="img-fluid" alt="" style="width: 150px; height: 150px; object-fit: cover"></a>
                    {% else %}
                        <img src="{% static 'bourseapp/images/technical.jpg' %}" class="img-fluid" alt="" style="width: 150px; height: 150px; object-fit: cover">
                    {% endif %}

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr>

            <p class="text-muted text-right text-justify mt-5 mb-5">{{ bazaar.description | safe }}</p>

            <div class="mt-5" style="text-align: center">
                <div class="w-75" style="display: inline-block">
                    {% if bazaar.aparatEmbedCode %}
                        {{ bazaar.aparatEmbedCode|safe }}
                    {% endif %}
                </div>

            </div>


        </section>
        <!--Section: Content-->



    </div>


    <!-- base url address -->
    <input type="hidden" id="url-base" data-url="http://{{ request.get_host }}/" />

    <!-- selected category id -->
{#    <input type="hidden" id="category-selected-id" selected-id="-1">#}


{% endblock %}

{% block javascript %}

    <!-- fill uploaded image -->
    <script>
        $('img').each(function(){
            if ($(this).attr('src').indexOf("media/uploads") > -1){
                {#alert($(this).attr('src'));#}
                $(this).css({
                    'width' : '100%',
                    'height' : '100%'
                });

            }
        });
    </script>
{% endblock %}

bourseapp/templates/bourseapp/bazaar_list.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% load auth_extras %}
{% block title %}
    <title>تحلیل های بازار</title>
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}

    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables.min.css' %}"><!-- MDBootstrap Datatables  -->
    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables-select.min.css' %}"><!-- MDBootstrap Datatables  -->

    <div class="alert alert-primary" role="alert">
        تحلیل های بازار
    </div>

    <!-- new/delete/edit buttons -->
    {% if request.user.is_superuser or request.user|has_group:"level1" %}
        <div class="text-center">
          <a href="{% url 'admin:bourseapp_bazaar_add' %}?user={{ user.id }}" class="btn btn-rounded btn-info btn-sm" ><i class="fas fa-plus-circle mr-1"></i> افزودن</a>
          <a id="technical-edit" href="{% url 'admin:bourseapp_bazaar_change'  1%}?next={{ request.path|urlencode }}"  class="btn btn-rounded btn-info btn-sm"><i class="fas fa-edit mr-1"></i> ویرایش</a>
          <a id="technical-delete" href="{% url 'admin:bourseapp_bazaar_delete' 1%}?next={{ request.path|urlencode }}"  class="btn btn-rounded btn-danger btn-sm"><i class="fas fa-trash mr-1"></i> حذف</a>
        </div>
    {% endif %}


    <!-- PAGE SIZE/ search -->
    <div class="container">
        <div class="row">
            <div class="col-6 select-outline">

                <label>تعداد صفحات</label>
                <select id="bazaar-selector-page-size"  class="browser-default custom-select"  onchange="bazaarPageSizeChanged(this.options[this.selectedIndex].value)">
                    <option value="10">10</option>
                    <option value="20" >20</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                <a id="bazaar-tag-a-page-size" class="d-none" href="?page-size=10">10</a>
                <script>
                    document.getElementById('bazaar-selector-page-size').value={{ page_size }};
                    function bazaarPageSizeChanged(page_size) {
                        {#alert(page_size)#}
                        let tag_a = document.getElementById("bazaar-tag-a-page-size");
                        let srchterm = $("#search-bazaar").val();
                        tag_a.href = "?page-size=" + page_size + "&search=" + srchterm;
                        tag_a.click();
                    }
                </script>

            </div>
            <div class="col-6">
                <!-- Search form -->
                <label>جست و جو</label>
                <div class="active-cyan-4">
                    <input id="search-bazaar" class="form-control" type="text" placeholder="جست و جو" aria-label="Search" value="{{ search }}">
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <!-- body -->
    <div class="">
        <div class="container py-1">

            <div class="row pagination-sm table-responsive" id="category-list">

                <table class="table table-sm table-hover table-striped"  id="bazaar-table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">نماد</th>
                        <th scope="col">عنوان</th>
                        <th scope="col">تاریخ</th>
                        <th scope="col">توضیحات</th>
                        <th scope="col">تصویر</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for tech in bazaar %}

                        {% if tech.isSuperUserPermition %}
                            {% if request.user.is_superuser or request.user|has_group:"level1" or request.user|has_group:"vip" %}

                                <tr>
                                    <input class="bazaarId" type="hidden" dataId={{ tech.id }}>
                                    <th scope="row" >{{ forloop.counter }} <span class="badge yellow mr-1"><small style="color: black">VIP</small></span></th>
                                    <td class="" >{{ tech.company.symbol }}</td>
                                    <td class="" ><a href="{% url 'bourseapp:technical-detail' tech.id %}">{{ tech.title }}</a></td>
                                    <td class="" style="font-family: 'IRANSansNum';">{{ tech.createAt|to_jalali:'%y/%m/%d' }}</td>
                                    <td class="">{{ tech.description | truncatechars:60 }}</td>
                                    {% if tech.pic %}
                                        <td ><a href="{{ tech.pic.url }}" target="_blank"><i class="fa fa-image"></i></a></td>
                                    {% else %}
                                        <td ><a href="#"></a></td>

                                    {% endif %}
                                </tr>

                            {% endif %}
                        {% else %}

                            <tr>
                                <input class="technicalId" type="hidden" dataId={{ tech.id }}>
                                <th scope="row" >{{ forloop.counter }}</th>
                                <td class="" >{{ tech.company.symbol }}</td>
                                <td class="" ><a href="{% url 'bourseapp:bazaar-detail' tech.id %}">{{ tech.title }}</a></td>
                                <td class="" style="font-family: 'IRANSansNum';">{{ tech.createAt|to_jalali:'%y/%m/%d' }}</td>
                                <td class="">{{ tech.description | truncatechars:60 }}</td>
                                {% if tech.pic %}
                                    <td ><a href="{{ tech.pic.url }}" target="_blank"><i class="fa fa-image"></i></a></td>
                                {% else %}
                                    <td ><a href="#"></a></td>

                                {% endif %}
                            </tr>

                        {% endif %}
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>

    <!-- pagination -->
    <div class="d-flex justify-content-center">
        {% if bazaar.has_other_pages %}
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-circle pg-blue">
                    <li class="page-item"><a class="page-link"  href="?page=1&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-bazaar').value">First</a></li>
                    {% if bazaar.has_previous %}
                        <li class="page-item">
                            <a class="page-link" aria-label="Previous" href="?page={{ bazaar.previous_page_number }}&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-bazaar').value">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                        <a class="page-link" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}

                    <!-- center page numbers -->
                    {% for i in bazaar.paginator.page_range %}
                        {% if bazaar.number == i %}
                            <li class="page-item active"><a class="page-link">{{ i }}</a></li>

                        {% else %}
                            <li class="page-item"><a class="page-link"  href="?page={{ i }}&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-bazaar').value">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <!-- center page numbers -->
                    {% if bazaar.has_next %}
                        <a class="page-link" aria-label="Next"  href="?page={{ bazaar.next_page_number }}&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-bazaar').value">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}

                    <li class="page-item"><a class="page-link">Last</a></li>
                </ul>
            </nav>
        {% endif %}
    </div>


    <!-- base url address -->
    <input type="hidden" id="url-base" data-url="http://{{ request.get_host }}/" />

    <!-- selected category id -->
{#    <input type="hidden" id="category-selected-id" selected-id="-1">#}

    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'bourseapp/js/jquery.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/mdb.min.js' %}"></script>
    <!-- MDB table core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/addons/datatables.min.js' %}"></script><!-- MDBootstrap Datatables  -->
    <!-- MDB table core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/addons/datatables-select.min.js' %}"></script><!-- MDBootstrap Datatables  -->

    <script>

        $("#bazaar-table tr").click(function(){
           $(this).addClass('table-primary').siblings().removeClass('table-primary');
           var value=$(this).find('input.bazaarId').attr("dataId");

           var url_mask_edit = "{% url 'admin:bourseapp_bazaar_change' 12345 %}".replace(/12345/, value.toString());
           $("#bazaar-edit").attr("href", url_mask_edit)

           var url_mask_delete = "{% url 'admin:bourseapp_bazaar_delete' 12345 %}".replace(/12345/, value.toString());
           $("#bazaar-delete").attr("href", url_mask_delete)

           {#alert(value)#}
                   });

        $('.ok').on('click', function(e){
            alert($("#bazaar-table tr.selected td:first").html());
        });

        // Material Select Initialization
        $(document).ready(function() {
            $('.mdb-select').materialSelect();
            $('.select-wrapper.md-form.md-outline input.select-dropdown').bind('focus blur', function () {
                $(this).closest('.select-outline').find('label').toggleClass('active');
                $(this).closest('.select-outline').find('.caret').toggleClass('active');
            });
        });



    </script>

    <!-- search -->
    <script>
        $("#search-bazaar").on('keyup', function (e) {
            if (e.keyCode === 13) {
                let srchterm = $("#search-bazaar").val();
                let tag_a = document.getElementById("bazaar-tag-a-page-size");
                tag_a.href = "?page-size=" + {{ page_size }} + "&search=" + srchterm;
                tag_a.click();
            }
        });
    </script>
{% endblock %}

bourseapp/templates/bourseapp/category_list.html
<!-- use base html template -->
{% extends 'bourseapp/base.html' %}
{% load jalali_tags %}
{% block title %}
    <title>گروه های بورسیا</title>
{% endblock %}
<!-- begin of body block -->
{% block body %}

    <!-- load static file in django -->
    {% load staticfiles %}


    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables.min.css' %}"><!-- MDBootstrap Datatables  -->
    <!-- Material Design Bootstrap table -->
    <link rel="stylesheet" href="{% static 'bourseapp/css/addons/datatables-select.min.css' %}"><!-- MDBootstrap Datatables  -->

    <div class="alert alert-primary" role="alert">
        گروه ها
    </div>

    <!-- new/delete/edit buttons -->
    <div class="text-center">
      <a href="{% url 'admin:bourseapp_category_add' %}?user={{ user.id }}" class="btn btn-rounded btn-info btn-sm" ><i class="fas fa-plus-circle mr-1"></i> افزودن</a>
      <a id="category-edit" href="{% url 'admin:bourseapp_category_change'  1%}?next={{ request.path|urlencode }}"  class="btn btn-rounded btn-info btn-sm"><i class="fas fa-edit mr-1"></i> ویرایش</a>
      <a id="category-delete" href="{% url 'admin:bourseapp_category_delete' 1%}?next={{ request.path|urlencode }}"  class="btn btn-rounded btn-danger btn-sm"><i class="fas fa-trash mr-1"></i> حذف</a>
    </div>


    <!-- PAGE SIZE/ search -->
    <div class="container">
        <div class="row">
            <div class="col-6 select-outline">

                <label>تعداد صفحات</label>
                <select id="category-selector-page-size"  class="browser-default custom-select"  onchange="categoryPageSizeChanged(this.options[this.selectedIndex].value)">
                    <option value="10">10</option>
                    <option value="20" >20</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                </select>
                <a id="category-tag-a-page-size" class="d-none" href="?page-size=10">10</a>
                <script>
                    document.getElementById('category-selector-page-size').value={{ page_size }};
                    function categoryPageSizeChanged(page_size) {
                        {#alert(page_size)#}
                        let tag_a = document.getElementById("category-tag-a-page-size");
                        let srchterm = $("#search-category").val();
                        tag_a.href = "?page-size=" + page_size + "&search=" + srchterm;
                        tag_a.click();
                    }
                </script>

            </div>
            <div class="col-6">
                {#                <input id="search-category"  style="width: 50%; margin: 0 auto; text-align: center" class="form-control float-left" type="text" placeholder="جست و جو" aria-label="Search" value="{{ search }}">#}
                <!-- Search form -->
                <label>جست و جو</label>
                <div class="active-cyan-4">
                    <input id="search-category" class="form-control" type="text" placeholder="جست و جو" aria-label="Search" value="{{ search }}">
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <!-- body -->
    <div class="">
        <div class="container py-1">

            <div class="row pagination-sm table-responsive" id="category-list">

                <table class="table table-sm table-hover table-striped"  id="category-table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">عنوان</th>
                        <th scope="col">تاریخ</th>
                        <th scope="col">توضیحات</th>
                        <th scope="col">تصویر</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for category in categories %}
                        <tr>
                            <input class="categoryId" type="hidden" dataId={{ category.id }}>
                            <th scope="row" >{{ forloop.counter }}</th>
                            <td class="title" ><a href="{% url 'bourseapp:category-detail' category.id%}">{{ category.title }}</a></td>
                            <td class="createAt" style="font-family: 'IRANSansNum';">{{ category.createAt|to_jalali:'%y/%m/%d' }}</td>
                            <td class="description">{{ category.description }}</td>
                            {% if category.pic %}
                                <td ><a href="{{ category.pic.url }}"><i class="fa fa-image"></i></a></td>
                            {% else %}
                                <td ><a href="#"></a></td>

                            {% endif %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>

    <!-- pagination -->
    <div class="d-flex justify-content-center">
        {% if categories.has_other_pages %}
            <nav aria-label="Page navigation example">
                <ul class="pagination pagination-circle pg-blue">
                    <li class="page-item"><a class="page-link"  href="?page=1&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-category').value">First</a></li>
                    {% if salaries.has_previous %}
                        <li class="page-item">
                            <a class="page-link" aria-label="Previous" href="?page={{ categories.previous_page_number }}&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-category').value">
                                <span aria-hidden="true">&laquo;</span>
                                <span class="sr-only">Previous</span>
                            </a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                        <a class="page-link" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    {% endif %}

                    <!-- center page numbers -->
                    {% for i in categories.paginator.page_range %}
                        {% if categories.number == i %}
                            <li class="page-item active"><a class="page-link">{{ i }}</a></li>

                        {% else %}
                            <li class="page-item"><a class="page-link"  href="?page={{ i }}&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-category').value">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}

                    <!-- center page numbers -->
                    {% if categories.has_next %}
                        <a class="page-link" aria-label="Next"  href="?page={{ categories.next_page_number }}&page-size={{ page_size }}" onclick="this.href += '&search=' + document.getElementById('search-category').value">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                    {% endif %}

                    <li class="page-item"><a class="page-link">Last</a></li>
                </ul>
            </nav>
        {% endif %}
    </div>


    <!-- base url address -->
    <input type="hidden" id="url-base" data-url="http://{{ request.get_host }}/" />

    <!-- selected category id -->
{#    <input type="hidden" id="category-selected-id" selected-id="-1">#}

    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'bourseapp/js/jquery.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/mdb.min.js' %}"></script>
    <!-- MDB table core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/addons/datatables.min.js' %}"></script><!-- MDBootstrap Datatables  -->
    <!-- MDB table core JavaScript -->
    <script type="text/javascript" src="{% static 'bourseapp/js/addons/datatables-select.min.js' %}"></script><!-- MDBootstrap Datatables  -->

    <script>

        $("#category-table tr").click(function(){
           $(this).addClass('table-primary').siblings().removeClass('table-primary');
           var value=$(this).find('input.categoryId').attr("dataId");

           var url_mask_edit = "{% url 'admin:bourseapp_category_change' 12345 %}".replace(/12345/, value.toString());
           $("#category-edit").attr("href", url_mask_edit)

           var url_mask_delete = "{% url 'admin:bourseapp_category_delete' 12345 %}".replace(/12345/, value.toString());
           $("#category-delete").attr("href", url_mask_delete)

           {#alert(value)#}
                   });

        $('.ok').on('click', function(e){
            alert($("#category-table tr.selected td:first").html());
        });

        // Material Select Initialization
        $(document).ready(function() {
            $('.mdb-select').materialSelect();
            $('.select-wrapper.md-form.md-outline input.select-dropdown').bind('focus blur', function () {
                $(this).closest('.select-outline').find('label').toggleClass('active');
                $(this).closest('.select-outline').find('.caret').toggleClass('active');
            });
        });



    </script>

    <!-- search -->
    <script>
        $("#search-category").on('keyup', function (e) {
            if (e.keyCode === 13) {
                let srchterm = $("#search-category").val();
                let tag_a = document.getElementById("category-tag-a-page-size");
                tag_a.href = "?page-size=" + {{ page_size }} + "&search=" + srchterm;
                tag_a.click();
            }
        });
    </script>
{% endblock %}